version: '3'

services:
  backend:
    build: .
    container_name: delevery_api
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - .:/app-backend
    environment:
      DATABASE_LOCAL_HOST_URL: ${DATABASE_LOCAL_HOST_URL}
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    container_name: delivery_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
